# Color maps for general visuals
color_blind_map = {
    "SITE": "grey",
    "LOAD": "#3B3B9E",
    "FLEX_LOAD": "#6464FB",
    "GENERATOR": "#009503",
    "INTERMITTENT": "#CCCC2E",
    "INTERMITTENT POTENTIAL": "#ADAD27",
    "STORAGE": "#A2A2FB",
    "MAINGRID": "#4e4e4e",
    "LONG_TERM": "#292929",
    "DAY_AHEAD": "#676767",
    "FCR": "#A9A9AA",
    "AFRR": "rgba(169,169,170, 0.75)",
    "SPOT": "#00CBA7",
    "SPOT + TURPE": "#00AF8E",
    "CONGESTIONS": "grey",
    "CLEAR": "rgba(200,200,200, 1)",
    "FLEX": "rgba(255,161,90, 0.5)",
}

color_map_default = color_blind_map

# Colors for optimization costs details visualization
color_map_costs = {
    "network_total_trade_costs": "#1f77b4",
    "network_total_fcr_costs": "#FECB52",
    "contract_total_net_costs": "#8c564b",
    "non_lin_gen_var_costs": "#FF97FF",
    "disp_gen_start_up_costs": "#FF6692",
    "lin_gen_var_costs": "#B6E880",
    "conv_var_cost": "#AB63FA",
    "inter_gen_var_cost": "#EF553B",
    "storage_use_penalties": "#A2A2FB",
    "storage_power_change_penalties": "#00CC96",
    "imbalance_total_net_costs": "#FFA15A",
    "day_ahead_total_trade_costs": "#19D3F3",
    "day_ahead_trade_costs": "#19D3F3",
    "day_ahead_trade_revenues": "#19D3F3",
    "day_ahead_total_fcr_costs": "#FECB52",
    "fcr_power_eng_deficit_total_costs": "#FECB52",
    "h2_energy_total_costs": "#FF6692",
    "electricity_total_tariff_costs": "#19D3F3",
    "electricity_total_net_revenue": "#19D3F3",
    "thermal_gen_total_var_costs": "#009503",
    "thermal_gen_total_startup_costs": "#B6E880",
    "inter_prod_total_var_costs": "#CCCC2E",
    "inter_prod_total_curt_costs": "#ADAD27",
    "long_term_costs": "grey",
}
